# Generated by Django 3.1.7 on 2021-03-02 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_first_name', models.CharField(max_length=50)),
                ('customer_last_name', models.CharField(max_length=50)),
                ('address', models.JSONField(blank=True, null=True)),
                ('customer_email', models.EmailField(max_length=254)),
                ('materials', models.JSONField(blank=True, null=True)),
                ('job_descripton', models.TextField()),
                ('dateOfJob', models.DateField()),
                ('removal_included', models.BooleanField(blank=True, null=True)),
                ('price_of_materials', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price_of_labour', models.DecimalField(decimal_places=2, max_digits=6)),
                ('quote_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('issued_by', models.CharField(max_length=255)),
                ('issued_by_phone_num', models.CharField(max_length=15)),
            ],
        ),
    ]
