# Generated by Django 3.0.5 on 2021-03-15 17:38

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('customer_first_name', models.CharField(max_length=50)),
                ('customer_last_name', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('customer_email', models.EmailField(max_length=254)),
                ('materials', models.TextField()),
                ('job_descripton', models.TextField()),
                ('date_of_job', models.DateField()),
                ('removal_included', models.BooleanField(blank=True, null=True)),
                ('price_of_removal', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('price_of_materials', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('price_of_labour', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('quote_price', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('issued_by', models.CharField(max_length=255)),
                ('issued_by_phone_num', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
