# Generated by Django 3.0.5 on 2021-04-17 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('customer_first_name', models.CharField(max_length=50)),
                ('customer_last_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=1000)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone_num', models.CharField(max_length=15)),
                ('materials', models.TextField()),
                ('job_description', models.TextField()),
                ('date_of_job', models.DateField()),
                ('removal_included', models.BooleanField(blank=True, default=False, null=True)),
                ('price_of_removal', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('price_of_materials', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price_of_labour', models.DecimalField(decimal_places=2, max_digits=6)),
                ('quote_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
